name: PlayerWarps
version: ${version}
main: com.oncearial.playerwarps.PlayerWarps
api-version: '1.21'
author: OnceArial
description: Player warps for Paper 1.21.1 through 26.2
website: https://github.com/onlyarial/Player-Warps
folia-supported: false
commands:
  pwarp:
    description: Player warps main command
    usage: /pwarp
    aliases: [pw, playerwarp, playerwarps]
permissions:
  playerwarps.use:
    default: true
  playerwarps.set:
    default: true
  playerwarps.delete:
    default: true
  playerwarps.gui:
    default: true
  playerwarps.favorite:
    default: true
  playerwarps.description:
    default: true
  playerwarps.feature:
    default: true
  playerwarps.setfeatured:
    default: true
  playerwarps.admin:
    default: op
